In [ ]:
# %pip install pandas pyarrow

In [2]:
import pandas as pd

df = pd.read_parquet("../../Data/sort_data/2025_data.parquet")
df.head()

,기준_날짜,시간대,집계_기준,시작_대여소_ID,종료_대여소_ID,전체_건수,전체_이용_분,전체_이용_거리,온도,습도,불쾌지수,강수량,적설량
0,2025-01-09,9,출발시간,ST-2775,ST-462,1,0 days 00:09:00,1379,-12.1,34,27.56414,0.0,0.0
1,2025-01-09,19,출발시간,ST-462,ST-2775,1,0 days 00:10:00,1368,-12.1,30,28.61530,0.0,0.0
2,2025-01-09,16,출발시간,ST-2782,ST-481,1,0 days 00:08:00,1281,-10.0,22,32.87600,0.0,0.0
3,2025-01-09,16,출발시간,ST-2261,ST-3126,1,0 days 00:08:00,1060,-10.0,22,32.87600,0.0,0.0
4,2025-01-09,17,출발시간,ST-32,ST-462,1,0 days 00:48:00,5946,-11.1,25,30.98675,0.0,0.0

In [3]:
df_1023 = \
    df[df.시작_대여소_ID == 'ST-1023']
df_1023.head()

,기준_날짜,시간대,집계_기준,시작_대여소_ID,종료_대여소_ID,전체_건수,전체_이용_분,전체_이용_거리,온도,습도,불쾌지수,강수량,적설량
453,2025-01-09,23,출발시간,ST-1023,ST-2259,1,0 days 00:14:00,2158,-12.3,35,27.07005,0.0,0.0
768,2025-01-09,23,출발시간,ST-1023,ST-2259,1,0 days 00:14:00,2158,-12.3,35,27.07005,0.0,0.0
1040,2025-01-10,23,출발시간,ST-1023,ST-2259,1,0 days 00:09:00,2146,-7.5,52,28.92800,0.0,0.0
1333,2025-01-10,23,출발시간,ST-1023,ST-2259,1,0 days 00:09:00,2146,-7.5,52,28.92800,0.0,0.0
1996,2025-01-11,14,출발시간,ST-1023,ST-1481,1,0 days 00:18:00,985,-2.5,35,38.40375,0.0,0.0

In [4]:
df_1024 = \
    df[df.시작_대여소_ID == 'ST-1024']
df_1024.head()

,기준_날짜,시간대,집계_기준,시작_대여소_ID,종료_대여소_ID,전체_건수,전체_이용_분,전체_이용_거리,온도,습도,불쾌지수,강수량,적설량
180,2025-01-09,20,출발시간,ST-1024,ST-453,1,0 days 00:42:00,4860,-12.1,31,28.35251,0.0,0.0
359,2025-01-09,6,출발시간,ST-1024,ST-1480,1,0 days 00:00:00,0,-11.4,39,27.08746,0.0,0.0
407,2025-01-09,20,출발시간,ST-1024,ST-453,1,0 days 00:42:00,4860,-12.1,31,28.35251,0.0,0.0
662,2025-01-09,6,출발시간,ST-1024,ST-1480,1,0 days 00:00:00,0,-11.4,39,27.08746,0.0,0.0
1233,2025-01-10,2,출발시간,ST-1024,ST-452,1,0 days 00:08:00,1256,-12.2,42,25.33924,0.0,0.0

In [5]:
df_450 = \
   df[df.시작_대여소_ID == 'ST-450']
df_450.head()

,기준_날짜,시간대,집계_기준,시작_대여소_ID,종료_대여소_ID,전체_건수,전체_이용_분,전체_이용_거리,온도,습도,불쾌지수,강수량,적설량
242,2025-01-09,17,출발시간,ST-450,ST-1483,1,0 days 00:14:00,1333,-11.1,25,30.98675,0.0,0.0
260,2025-01-09,16,출발시간,ST-450,ST-451,1,0 days 00:04:00,943,-10.0,22,32.87600,0.0,0.0
281,2025-01-09,8,출발시간,ST-450,ST-1481,1,0 days 00:04:00,590,-12.2,38,26.39436,0.0,0.0
348,2025-01-09,8,출발시간,ST-450,ST-453,1,0 days 00:05:00,773,-12.2,38,26.39436,0.0,0.0
422,2025-01-09,8,출발시간,ST-450,ST-1481,1,0 days 00:04:00,590,-12.2,38,26.39436,0.0,0.0

In [6]:
df_1024.to_csv("../../Data/2025_ST-1024.csv")
df_1024.to_csv("../../Data/2025_ST-1023.csv")
df_450.to_csv("../../Data/2025_ST-450.csv")

In [7]:
# %pip install pandas pyarrow
import pandas as pd

df = pd.read_parquet("../../Data/sort_data/2024_data.parquet")
df.head()

df_1023 = \
    df[df.시작_대여소_ID == 'ST-1023']
df_1023.head()
df_1024 = \
    df[df.시작_대여소_ID == 'ST-1024']
df_1024.head()
df_450 = \
   df[df.시작_대여소_ID == 'ST-450']
df_450.head()


df_1024.to_csv("../../Data/2024_ST-1024.csv")
df_1024.to_csv("../../Data/2024_ST-1023.csv")
df_450.to_csv("../../Data/2024_ST-450.csv")