---
### 이광태 테스트 노트

In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('../../Data/은평구_스테이션_군집화_1차.csv')

In [10]:
# 3구역 군집화 시각화
import folium

In [ ]:
seoul_map = folium.Map(
  location=[37.55,126.98],
  zoom_start=11
)

for 대여소_ID,위도,경도,연간_전체건수 in zip(data_result.대여소_ID, data_result.위도,data_result.경도,data_result.연간_전체건수):
  popup = folium.Popup(대여소_ID, max_width=200)
  folium.Marker(
    [위도, 경도],
    popup=popup
  ).add_to(seoul_map)

  
  folium.CircleMarker(
    [위도, 경도],
    radius=연간_전체건수/total*100*2.5,
    color = 'skyblue',
    fill=True,
    fill_color='skyblue',
    fill_opacity=0.4,
    tooltip=f"전체건수{연간_전체건수}",
  ).add_to(seoul_map)

# 3구역 station가져오기

,기준_날짜,집계_기준,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,기준_시간
0,20240101,출발시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,1.0,4.0,612.0,1645.0
1,20240101,도착시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,1.0,4.0,612.0,1650.0
2,20240101,도착시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,2.0,7.0,1248.0,1635.0
3,20240101,출발시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,2.0,7.0,1248.0,1630.0
4,20240101,도착시간,ST-2263,진관동_108_6,ST-481,구산동_062_1,1.0,12.0,2992.0,1400.0

In [76]:
data_result = pd.read_csv('../../Data/gtlee_data/gt_3구역_1027_2263_3126.csv')

In [73]:
print('ST-1027',data_result[(data_result.시작_대여소_ID == 'ST-1027')].shape)
print('ST-2263',data_result[(data_result.시작_대여소_ID == 'ST-2263')].shape)
print('ST-3126',data_result[(data_result.시작_대여소_ID == 'ST-3126')].shape)

ST-1027 (11564, 10)
ST-2263 (10410, 10)
ST-3126 (10556, 10)

In [77]:
data_result.head()

,기준_날짜,집계_기준,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,기준_시간
0,20240101,출발시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,1.0,4.0,612.0,1645.0
1,20240101,도착시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,1.0,4.0,612.0,1650.0
2,20240101,도착시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,2.0,7.0,1248.0,1635.0
3,20240101,출발시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,2.0,7.0,1248.0,1630.0
4,20240101,도착시간,ST-2263,진관동_108_6,ST-481,구산동_062_1,1.0,12.0,2992.0,1400.0

In [78]:
data_result.loc[:,'기준_시간_int'] = data_result.loc[:,'기준_시간'].astype(int)

# for i in data_result.index:
#   data_result.loc[i,'기준_날짜_str'] = data_result.loc[i,'기준_날짜'].astype(str)

In [82]:
data_result.loc[:,'기준_시간_str'] = data_result.loc[:,'기준_시간_int'].astype(str)

In [92]:
data_result.tail()

,기준_날짜,집계_기준,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,기준_시간,기준_시간_int,기준_시간_str
32525,20241231,출발시간,ST-3126,진관동_076_1,ST-1483,진관동_108_1,1.0,43.0,1560.0,1900.0,1900,1900
32526,20241231,출발시간,ST-3126,진관동_076_1,ST-453,진관동_011_3,1.0,3.0,639.0,735.0,735,0735
32527,20241231,출발시간,ST-2263,진관동_004_2,ST-453,진관동_011_3,1.0,6.0,916.0,1955.0,1955,1955
32528,20241231,도착시간,ST-3126,진관동_076_1,ST-453,진관동_011_3,1.0,2.0,495.0,950.0,950,0950
32529,20241231,도착시간,ST-3126,진관동_076_1,ST-3028,불광2동_008_1,1.0,5.0,975.0,800.0,800,0800

In [91]:

for index in data_result.index:
  if len(data_result.loc[index,'기준_시간_str']) == 3:
    data_result.loc[index,'기준_시간_str'] = '0'+data_result.loc[index,'기준_시간_str']

In [ ]:
# data_result['기준_날짜_str'] = pd.to_datetime(data_result['기준_날짜'].astype(str))

In [66]:
data_result.head()

,기준_날짜,집계_기준,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,기준_시간,기준_날짜_str,기준_시간_str,기준_시간_str_d,기준_시간_str_dd
0,20240101,출발시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,1.0,4.0,612.0,1645.0,2024-01-01,1645.0,1645:00,16:45:00
1,20240101,도착시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,1.0,4.0,612.0,1650.0,2024-01-01,1650.0,1650:00,16:50:00
2,20240101,도착시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,2.0,7.0,1248.0,1635.0,2024-01-01,1635.0,1635:00,16:35:00
3,20240101,출발시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,2.0,7.0,1248.0,1630.0,2024-01-01,1630.0,1630:00,16:30:00
4,20240101,도착시간,ST-2263,진관동_108_6,ST-481,구산동_062_1,1.0,12.0,2992.0,1400.0,2024-01-01,1400.0,1400:00,14:00:00

In [ ]:
#data_result.loc[:,'기준_시간_str_d'] = data_result.loc[:,'기준_시간_str'].str.replace('.0',':00')

In [ ]:
#data_result['기준_시간_str_dd'] = data_result['기준_시간_str_d'][:2] +':'+ data_result['기준_시간_str_d'][2:]

In [60]:
data_result.tail()

,기준_날짜,집계_기준,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,기준_시간,기준_날짜_str,기준_시간_str,기준_시간_str_d,기준_시간_str_dd
32525,20241231,출발시간,ST-3126,진관동_076_1,ST-1483,진관동_108_1,1.0,43.0,1560.0,1900.0,NaN,1900.0,1900:00,19:00:00
32526,20241231,출발시간,ST-3126,진관동_076_1,ST-453,진관동_011_3,1.0,3.0,639.0,735.0,NaN,735.0,735:00,73:5:00
32527,20241231,출발시간,ST-2263,진관동_004_2,ST-453,진관동_011_3,1.0,6.0,916.0,1955.0,NaN,1955.0,1955:00,19:55:00
32528,20241231,도착시간,ST-3126,진관동_076_1,ST-453,진관동_011_3,1.0,2.0,495.0,950.0,NaN,950.0,950:00,95:0:00
32529,20241231,도착시간,ST-3126,진관동_076_1,ST-3028,불광2동_008_1,1.0,5.0,975.0,800.0,NaN,800.0,800:00,80:0:00

In [94]:
#data_result.loc[:,'기준_시간_str_d'][0][:2] + ":" + data_result.loc[:,'기준_시간_str_d'][0][2:]

for index in data_result.index:
  data_result.loc[index,'기준_시간_str_d'] = data_result.loc[index,'기준_시간_str'][:2] +':'+ data_result.loc[index,'기준_시간_str'][2:] + ':00'
  print(data_result.loc[index,'기준_시간_str_d'])

16:45:00
16:50:00
16:35:00
16:30:00
14:00:00
13:15:00
13:50:00
18:05:00
18:15:00
04:00:00
22:40:00
22:35:00
23:45:00
23:55:00
01:00:00
22:00:00
22:10:00
5::00
04:25:00
12:00:00
11:25:00
11:25:00
11:25:00
11:05:00
11:40:00
11:40:00
11:40:00
11:35:00
12:50:00
13:10:00
12:30:00
12:45:00
10:55:00
09:55:00
09:50:00
10:15:00
20:25:00
21:00:00
23:30:00
23:25:00
21:35:00
22:00:00
22:05:00
21:50:00
20:15:00
12:40:00
12:40:00
11:45:00
12:05:00
12:05:00
12:00:00
12:00:00
13:35:00
13:20:00
13:15:00
13:15:00
09:20:00
09:10:00
11:25:00
11:20:00
10:40:00
10:30:00
17:00:00
16:30:00
16:35:00
17:10:00
14:35:00
14:35:00
15:45:00
15:45:00
15:55:00
15:35:00
18:30:00
18:40:00
18:20:00
18:15:00
18:15:00
18:05:00
18:10:00
19:45:00
19:50:00
19:55:00
20:10:00
20:00:00
20:00:00
20:00:00
19:30:00
19:20:00
08:10:00
08:10:00
08:05:00
08:05:00
08:15:00
08:10:00
08:10:00
07:40:00
07:35:00
07:50:00
08:40:00
08:35:00
08:40:00
08:50:00
08:45:00
08:45:00
08:45:00
08:20:00
08:20:00
08:20:00
08:30:00
08:30:00
07:35:00
05:55:00
05:50:00
45::00
40::00
07:20:00
07:20:00
07:20:00
07:15:00
07:30:00
07:25:00
07:25:00
07:25:00
07:30:00
06:55:00
07:00:00
06:45:00
06:50:00
02:20:00
09:40:00
09:45:00
15:40:00
15:30:00
12:50:00
13:00:00
12:15:00
12:25:00
07:35:00
07:25:00
07:45:00
07:35:00
08:10:00
01:45:00
02:15:00
01:35:00
08:15:00
07:00:00
06:45:00
07:15:00
07:05:00
07:10:00
06:40:00
20:20:00
20:20:00
20:55:00
20:55:00
19:40:00
19:40:00
19:55:00
19:50:00
22:10:00
21:55:00
22:05:00
21:45:00
17:55:00
18:00:00
17:00:00
19:10:00
18:20:00
18:30:00
06:50:00
06:30:00
06:30:00
05:45:00
06:15:00
06:15:00
07:30:00
07:35:00
07:20:00
07:10:00
01:15:00
01:25:00
21:20:00
21:55:00
22:00:00
20:35:00
20:35:00
20:10:00
21:15:00
20:45:00
08:15:00
08:25:00
08:35:00
08:35:00
08:35:00
07:50:00
07:40:00
09:10:00
09:10:00
08:45:00
17:05:00
17:15:00
17:20:00
17:35:00
18:50:00
18:15:00
18:00:00
18:00:00
18:05:00
18:45:00
10:50:00
10:45:00
12:35:00
12:35:00
06:40:00
06:35:00
06:35:00
06:35:00
06:35:00
03:10:00
02:45:00
06:00:00
18:35:00
18:35:00
19:35:00
19:55:00
18:50:00
18:40:00
19:05:00
15:40:00
15:35:00
15:45:00
16:30:00
13:15:00
16:20:00
08:45:00
08:55:00
08:50:00
08:05:00
08:25:00
08:30:00
08:10:00
08:10:00
12:15:00
12:35:00
12:40:00
12:30:00
20:15:00
21:10:00
21:00:00
22:20:00
22:20:00
22:30:00
22:30:00
23:35:00
23:40:00
12:00:00
22:05:00
22:15:00
21:50:00
22:00:00
17:30:00
17:25:00
17:55:00
17:55:00
17:55:00
16:50:00
16:45:00
16:40:00
17:15:00
17:05:00
17:00:00
17:00:00
18:10:00
18:05:00
18:30:00
02:55:00
11:25:00
11:15:00
10:40:00
10:35:00
03:05:00
09:15:00
09:35:00
09:25:00
09:30:00
09:10:00
08:40:00
10:05:00
10:00:00
08:10:00
08:25:00
14:00:00
14:05:00
16:20:00
16:25:00
16:10:00
16:20:00
12:40:00
13:00:00
12:50:00
12:55:00
22:25:00
22:10:00
19:00:00
11:10:00
11:15:00
11:15:00
10:55:00
17:45:00
17:30:00
18:40:00
13:45:00
13:55:00
13:55:00
14:10:00
14:20:00
14:15:00
22:00:00
21:55:00
17:00:00
23:50:00
23:35:00
18:10:00
11:05:00
12:05:00
10:50:00
10:55:00
10:40:00
07:35:00
07:40:00
08:45:00
08:15:00
15:40:00
15:30:00
15:45:00
15:15:00
15:20:00
15:20:00
13:20:00
13:00:00
13:00:00
13:20:00
12:55:00
12:20:00
23:50:00
23:45:00
12:20:00
12:25:00
08:40:00
08:40:00
08:45:00
08:35:00
08:35:00
10:25:00
10:40:00
18:50:00
20:05:00
18:25:00
06:05:00
04:25:00
20:15:00
04:00:00
07:40:00
07:55:00
07:50:00
07:25:00
07:35:00
07:55:00
08:20:00
08:00:00
08:05:00
06:50:00
06:50:00
06:35:00
08:35:00
08:20:00
07:25:00
07:50:00
20:00:00
18:40:00
18:45:00
23:20:00
23:35:00
22:35:00
22:45:00
20:15:00
14:15:00
14:15:00
14:25:00
14:20:00
13:30:00
12:20:00
12:50:00
17:20:00
17:15:00
15:20:00
13:55:00
14:00:00
10:15:00
10:45:00
10:40:00
16:55:00
17:05:00
16:20:00
07:25:00
03:10:00
03:00:00
08:50:00
08:40:00
10:00:00
08:00:00
07:45:00
07:50:00
08:30:00
08:35:00
08:35:00
08:15:00
20:20:00
20:05:00
20:40:00
20:40:00
20:25:00
21:00:00
21:05:00
21:25:00
21:25:00
21:20:00
18:45:00
19:00:00
18:55:00
19:05:00
18:05:00
18:15:00
18:00:00
08:40:00
17:35:00
17:30:00
08:05:00
08:15:00
08:00:00
13:30:00
15:25:00
15:20:00
15:25:00
16:45:00
13:35:00
15:15:00
11:40:00
11:50:00
11:50:00
11:50:00
11:35:00
10:25:00
10:25:00
10:10:00
10:15:00
10:20:00
16:50:00
12:25:00
12:25:00
12:00:00
12:10:00
02:00:00
20:00:00
20:00:00
02:20:00
18:45:00
18:40:00
23:05:00
23:10:00
22:30:00
07:20:00
07:25:00
06:35:00
06:40:00
22:30:00
21:45:00
21:50:00
20:45:00
21:00:00
22:20:00
22:20:00
13:50:00
13:55:00
14:00:00
13:50:00
13:50:00
12:50:00
12:45:00
14:45:00
14:50:00
15:00:00
14:10:00
14:10:00
14:10:00
14:15:00
14:05:00
15:40:00
14:35:00
14:35:00
14:45:00
16:55:00
17:00:00
16:35:00
16:40:00
21:50:00
21:50:00
21:50:00
22:05:00
20:55:00
21:25:00
19:05:00
19:00:00
18:55:00
18:55:00
18:55:00
18:45:00
20:15:00
20:20:00
19:25:00
17:45:00
18:10:00
18:00:00
18:00:00
09:55:00
10:10:00
09:50:00
10:40:00
10:40:00
10:45:00
10:25:00
10:15:00
11:50:00
11:10:00
10:50:00
10:50:00
11:30:00
11:30:00
11:35:00
11:20:00
11:20:00
11:20:00
01:30:00
01:45:00
04:00:00
04:20:00
11:55:00
16:05:00
11:50:00
18:10:00
18:00:00
18:50:00
18:40:00
18:40:00
18:40:00
16:10:00
17:30:00
17:35:00
02:30:00
02:35:00
01:00:00
02:05:00
02:00:00
01:10:00
09:05:00
08:45:00
21:20:00
21:10:00
14:15:00
14:15:00
13:40:00
13:45:00
16:20:00
09:20:00
12:20:00
12:10:00
12:55:00
12:05:00
12:05:00
20:50:00
20:55:00
20:10:00
20:20:00
19:05:00
19:55:00
19:55:00
20:05:00
19:55:00
19:15:00
16:55:00
22:35:00
22:40:00
22:25:00
22:30:00
07:25:00
08:20:00
07:45:00
08:10:00
08:15:00
08:15:00
11:25:00
07:45:00
10:05:00
09:35:00
09:30:00
09:30:00
08:35:00
08:40:00
08:30:00
08:35:00
08:45:00
22:05:00
22:30:00
04:20:00
07:30:00
04:00:00
19:20:00
19:20:00
19:00:00
20:10:00
20:10:00
20:35:00
20:35:00
20:25:00
20:30:00
20:30:00
20:30:00
19:35:00
20:00:00
20:05:00
16:45:00
16:40:00
16:55:00
18:20:00
18:10:00
18:00:00
18:05:00
18:00:00
15:50:00
15:20:00
16:10:00
16:10:00
16:15:00
16:15:00
16:05:00
16:05:00
14:00:00
14:05:00
15:05:00
12:50:00
13:00:00
11:50:00
16:30:00
20:50:00
20:50:00
16:25:00
16:25:00
13:55:00
13:50:00
03:40:00
03:45:00
01:45:00
01:45:00
01:45:00
01:50:00
01:40:00
10:30:00
10:55:00
10:05:00
10:00:00
10:10:00
10:05:00
17:15:00
16:55:00
12:15:00
12:05:00
11:25:00
11:35:00
14:15:00
14:05:00
07:45:00
07:50:00
06:45:00
06:50:00
06:20:00
06:25:00
07:25:00
07:20:00
08:45:00
08:50:00
08:55:00
08:25:00
08:25:00
08:25:00
08:20:00
08:35:00
19:15:00
19:30:00
19:20:00
18:10:00
17:05:00
17:00:00
17:05:00
16:40:00
16:40:00
16:45:00
16:45:00
16:45:00
16:50:00
18:00:00
18:00:00
18:10:00
18:05:00
17:25:00
22:10:00
22:35:00
20:00:00
19:45:00
21:15:00
21:20:00
20:35:00
20:35:00
20:30:00
08:45:00
09:50:00
10:15:00
09:55:00
10:00:00
02:25:00
02:30:00
08:20:00
07:25:00
07:30:00
15:30:00
16:15:00
16:25:00
15:50:00
12:45:00
12:55:00
14:05:00
14:15:00
15:00:00
15:15:00
15:15:00
14:50:00
14:25:00
14:45:00
12:10:00
12:00:00
12:25:00
12:15:00
11:40:00
11:30:00
11:45:00
17:05:00
17:05:00
17:20:00
17:05:00
17:50:00
17:55:00
15:40:00
15:20:00
15:35:00
16:40:00
16:35:00
16:10:00
16:10:00
16:15:00
07:25:00
07:25:00
07:30:00
08:10:00
08:05:00
06:20:00
10:05:00
10:20:00
11:25:00
08:30:00
08:45:00
08:25:00
08:55:00
19:25:00
20:10:00
19:30:00
18:10:00
18:10:00
18:00:00
18:00:00
18:35:00
18:25:00
22:25:00
22:25:00
22:35:00
22:30:00
22:35:00
22:40:00
22:00:00
21:50:00
22:05:00
22:10:00
22:50:00
22:40:00
20:45:00
20:30:00
21:30:00
21:05:00
21:25:00
06:15:00
06:55:00
07:10:00
08:15:00
08:15:00
07:45:00
07:30:00
07:15:00
02:00:00
02:10:00
02:15:00
01:50:00
23:20:00
23:20:00
23:10:00
23:15:00
14:20:00
14:05:00
14:15:00
14:50:00
14:50:00
13:55:00
13:50:00
16:10:00
15:55:00
15:55:00
15:55:00
16:15:00
14:55:00
15:25:00
10:00:00
09:50:00
09:45:00
09:50:00
09:50:00
10:35:00
10:25:00
10:20:00
10:25:00
10:30:00
08:50:00
08:45:00
09:45:00
09:45:00
09:40:00
12:05:00
12:55:00
12:55:00
13:10:00
12:50:00
11:30:00
11:45:00
11:35:00
16:50:00
16:45:00
14:20:00
14:25:00
09:15:00
09:05:00
01:05:00
55::00
04:00:00
04:20:00
12:35:00
12:30:00
12:40:00
12:50:00
12:50:00
10:20:00
10:10:00
10:05:00
10:55:00
11:20:00
11:15:00
11:10:00
17:40:00
17:15:00
17:15:00
17:35:00
17:25:00
15:45:00
16:05:00
16:45:00
16:15:00
16:40:00
21:35:00
21:20:00
18:50:00
18:55:00
08:25:00
08:45:00
01:35:00
01:15:00
01:05:00
55::00
09:35:00
13:40:00
13:40:00
13:40:00
14:40:00
14:45:00
13:50:00
10:05:00
12:05:00
12:00:00
12:15:00
12:10:00
14:40:00
14:35:00
18:10:00
16:15:00
16:55:00
10:00:00
10:10:00
10:15:00
09:55:00
08:35:00
08:45:00
08:30:00
08:50:00
08:50:00
13:15:00
13:05:00
10:35:00
10:45:00
08:15:00
07:20:00
23:15:00
23:20:00
01:25:00
01:15:00
06:45:00
07:15:00
06:50:00
19:05:00
20:00:00
18:15:00
18:15:00
20:05:00
21:50:00
21:40:00
21:10:00
21:20:00
16:25:00
15:55:00
14:30:00
14:50:00
14:35:00
13:55:00
15:40:00
15:05:00
14:55:00
19:45:00
19:35:00
19:40:00
19:40:00
19:35:00
17:45:00
17:45:00
18:00:00
17:35:00
17:30:00
18:10:00
08:10:00
08:05:00
08:05:00
07:40:00
07:35:00
08:35:00
08:40:00
08:10:00
06:45:00
06:45:00
04:10:00
04:00:00
11:05:00
11:05:00
11:00:00
10:50:00
11:10:00
13:15:00
12:20:00
12:50:00
12:45:00
10:40:00
09:10:00
09:20:00
08:45:00
09:50:00
09:25:00
22:05:00
20:45:00
20:55:00
20:15:00
21:35:00
21:50:00
21:25:00
21:15:00
21:25:00
18:00:00
18:00:00
18:10:00
18:10:00
18:10:00
18:10:00
17:35:00
17:40:00
18:00:00
17:50:00
18:15:00
18:15:00
18:15:00
18:20:00
18:20:00
18:20:00
17:15:00
17:20:00
17:20:00
17:30:00
17:25:00
16:45:00
16:40:00
17:00:00
16:55:00
22:05:00
21:30:00
22:10:00
19:05:00
20:05:00
08:05:00
08:05:00
08:20:00
08:20:00
08:15:00
08:45:00
08:45:00
09:00:00
09:00:00
08:50:00
08:55:00
08:25:00
08:20:00
08:40:00
08:35:00
02:05:00
02:15:00
13:45:00
13:35:00
13:35:00
12:50:00
13:25:00
13:25:00
13:20:00
14:30:00
14:35:00
10:05:00
10:10:00
09:50:00
10:25:00
10:40:00
09:20:00
09:20:00
09:20:00
09:05:00
09:25:00
09:25:00
09:35:00
10:45:00
12:05:00
12:00:00
11:55:00
12:00:00
12:40:00
12:40:00
12:45:00
12:45:00
12:35:00
08:20:00
08:30:00
08:05:00
08:15:00
08:10:00
09:10:00
09:30:00
09:35:00
09:40:00
08:50:00
01:50:00
01:55:00
04:00:00
07:40:00
07:35:00
04:20:00
19:20:00
19:20:00
19:20:00
19:45:00
19:45:00
19:30:00
18:50:00
20:55:00
20:10:00
20:05:00
20:25:00
20:25:00
16:45:00
16:55:00
16:50:00
17:20:00
17:10:00
16:25:00
16:25:00
16:10:00
16:45:00
16:30:00
18:10:00
18:00:00
17:25:00
17:25:00
14:10:00
14:15:00
13:55:00
13:55:00
10:15:00
10:20:00
12:00:00
12:10:00
16:00:00
21:55:00
22:05:00
22:25:00
22:25:00
22:30:00
22:30:00
14:55:00
15:00:00
15:50:00
09:30:00
08:15:00
08:10:00
09:50:00
09:55:00
09:45:00
09:40:00
10:05:00
01:35:00
01:20:00
17:50:00
18:00:00
17:30:00
17:40:00
18:20:00
18:15:00
16:35:00
16:15:00
17:20:00
17:20:00
17:20:00
22:05:00
22:10:00
12:25:00
12:40:00
12:05:00
12:15:00
13:00:00
12:55:00
12:55:00
11:05:00
11:15:00
11:20:00
11:00:00
11:30:00
12:00:00
11:35:00
15:10:00
14:40:00
15:00:00
15:45:00
15:45:00
13:50:00
13:55:00
13:55:00
13:35:00
13:30:00
14:30:00
14:05:00
14:10:00
17:00:00
15:15:00
16:30:00
16:00:00
16:05:00
16:10:00
21:00:00
21:15:00
19:05:00
19:15:00
10:50:00
10:20:00
10:40:00
10:35:00
14:50:00
14:35:00
12:55:00
12:50:00
11:00:00
11:55:00
15:00:00
15:05:00
15:55:00
14:40:00
14:35:00
14:45:00
14:25:00
55::00
01:05:00
10:05:00
09:35:00
20:10:00
20:05:00
20:50:00
20:55:00
20:40:00
20:40:00
19:20:00
19:15:00
19:30:00
19:15:00
19:15:00
21:20:00
21:05:00
21:05:00
21:05:00
21:05:00
21:15:00
17:15:00
17:20:00
17:35:00
16:25:00
16:00:00
16:05:00
16:30:00
18:40:00
18:25:00
18:25:00
18:50:00
18:00:00
18:05:00
18:05:00
17:50:00
17:50:00
17:50:00
18:20:00
18:10:00
18:10:00
18:15:00
18:05:00
17:45:00
18:45:00
18:40:00
18:50:00
17:40:00
18:45:00
18:35:00
18:25:00
16:20:00
16:35:00
16:25:00
15:50:00
15:45:00
16:00:00
17:25:00
17:10:00
17:20:00
17:40:00
16:50:00
16:45:00
16:55:00
17:00:00
21:50:00
21:45:00
21:55:00
21:40:00
22:05:00
22:05:00
22:05:00
22:10:00
21:05:00
21:10:00
21:25:00
21:25:00
21:25:00
22:10:00
23:50:00
23:50:00
23:40:00
23:35:00
23:40:00
22:15:00
22:35:00
19:50:00
19:00:00
20:35:00
20:35:00
20:40:00
20:05:00
20:00:00
20:10:00
20:15:00
08:25:00
08:25:00
08:20:00
08:15:00
08:20:00
08:35:00
08:15:00
08:10:00
08:10:00
09:40:00
09:40:00
09:30:00
09:25:00
09:30:00
08:40:00
08:45:00
08:35:00
08:40:00
08:50:00
08:50:00
07:30:00
07:30:00
07:30:00
07:25:00
07:35:00
07:40:00
06:25:00
06:15:00
06:45:00
06:50:00
13:40:00
13:45:00
15:05:00
14:40:00
14:40:00
14:45:00
14:35:00
15:00:00
14:45:00
14:50:00
10:40:00
09:45:00
10:35:00
12:50:00
12:45:00
12:45:00
12:35:00
09:30:00
09:30:00
09:25:00
10:00:00
10:05:00
10:05:00
08:40:00
08:45:00
08:45:00
08:35:00
08:35:00
08:45:00
08:55:00
08:50:00
13:15:00
13:00:00
13:00:00
12:25:00
12:20:00
12:10:00
23:05:00
23:20:00
23:10:00
23:35:00
23:35:00
23:30:00
22:05:00
22:30:00
22:30:00
22:20:00
22:20:00
08:05:00
08:05:00
07:45:00
08:10:00
08:25:00
08:10:00
08:20:00
06:55:00
06:50:00
06:20:00
06:15:00
07:30:00
07:40:00
07:25:00
18:55:00
18:50:00
21:25:00
21:55:00
21:50:00
21:55:00
21:45:00
21:30:00
21:35:00
20:10:00
19:50:00
19:55:00
20:15:00
15:45:00
15:50:00
16:20:00
14:25:00
14:35:00
17:45:00
17:55:00
17:35:00
17:40:00
17:15:00
12:10:00
11:45:00
11:55:00
10:35:00
10:45:00
11:25:00
11:20:00
11:20:00
11:20:00
11:25:00
14:05:00
14:10:00
07:40:00
07:35:00
07:30:00
07:25:00
07:30:00
08:00:00
08:10:00
07:55:00
07:15:00
07:15:00
07:20:00
06:55:00
06:50:00
08:10:00
09:00:00
08:50:00
08:50:00
08:50:00
09:45:00
09:40:00
09:55:00
09:25:00
09:30:00
09:25:00
08:25:00
08:25:00
08:20:00
08:20:00
08:30:00
08:30:00
20:20:00
20:00:00
21:00:00
20:55:00
21:00:00
20:40:00
20:40:00
20:00:00
19:20:00
19:15:00
19:45:00
20:00:00
19:40:00
22:40:00
22:45:00
22:25:00
21:40:00
21:10:00
22:05:00
22:05:00
22:05:00
21:55:00
17:05:00
17:10:00
17:10:00
16:00:00
15:50:00
15:50:00
15:50:00
15:55:00
16:40:00
16:25:00
16:20:00
16:30:00
18:35:00
18:50:00
18:45:00
18:45:00
03:05:00
03:00:00
01:45:00
01:45:00
13:15:00
13:20:00
11:30:00
11:25:00
10:55:00
12:10:00
11:50:00
12:05:00
12:05:00
12:00:00
15:05:00
15:10:00
14:00:00
13:50:00
08:15:00
08:15:00
07:20:00
07:20:00
06:50:00
07:15:00
07:10:00
07:10:00
07:05:00
07:45:00
07:50:00
07:40:00
07:45:00
09:55:00
09:50:00
09:55:00
09:30:00
09:45:00
08:50:00
08:35:00
08:45:00
09:10:00
08:55:00
09:05:00
09:00:00
20:20:00
19:55:00
21:00:00
19:05:00
19:15:00
19:05:00
19:25:00
22:15:00
21:25:00
21:25:00
21:30:00
21:10:00
21:15:00
22:10:00
17:05:00
17:05:00
17:10:00
17:10:00
17:30:00
17:35:00
17:15:00
17:25:00
16:35:00
16:35:00
16:40:00
18:50:00
18:45:00
18:05:00
06:50:00
30::00
40::00
04:25:00
04:00:00
11:40:00
12:35:00
12:25:00
12:30:00
10:40:00
11:25:00
11:35:00
11:20:00
14:20:00
14:30:00
14:30:00
14:10:00
14:10:00
14:10:00
14:10:00
14:15:00
14:10:00
13:00:00
04:55:00
03:15:00
07:05:00
07:10:00
05:00:00
06:30:00
06:25:00
06:20:00
06:10:00
03:05:00
09:20:00
09:25:00
10:15:00
10:30:00
10:05:00
08:10:00
08:40:00
19:20:00
22:10:00
22:15:00
22:20:00
22:05:00
14:45:00
14:35:00
14:35:00
17:20:00
18:00:00
18:00:00
17:45:00
16:45:00
16:30:00
17:00:00
16:50:00
17:45:00
15:20:00
16:40:00
16:10:00
16:00:00
16:05:00
16:15:00
21:35:00
21:35:00
21:35:00
21:35:00
21:50:00
21:50:00
18:35:00
18:30:00
20:25:00
20:10:00
10:00:00
10:05:00
11:10:00
11:10:00
01:30:00
50::00
01:00:00
01:05:00
06:50:00
06:35:00
14:20:00
14:20:00
14:15:00
14:15:00
13:55:00
14:40:00
11:55:00
12:00:00
13:25:00
09:25:00
09:50:00
11:55:00
12:05:00
22:10:00
22:00:00
15:40:00
15:40:00
15:35:00
14:45:00
14:40:00
17:00:00
21:00:00
21:00:00
20:55:00
20:55:00
21:05:00
21:10:00
21:10:00
20:30:00
20:30:00
20:30:00
20:25:00
20:25:00
20:45:00
20:50:00
20:40:00
22:05:00
22:05:00
21:25:00
13:30:00
13:20:00
13:05:00
12:25:00
14:30:00
14:40:00
09:30:00
09:45:00
11:55:00
11:45:00
12:25:00
12:15:00
11:45:00
11:45:00
16:00:00
15:00:00
15:10:00
15:15:00
15:05:00
16:05:00
16:30:00
07:25:00
07:50:00
19:05:00
18:55:00
19:55:00
20:10:00
20:05:00
19:35:00
19:20:00
18:20:00
18:25:00
18:20:00
18:30:00
18:15:00
18:10:00
18:10:00
18:10:00
09:15:00
09:30:00
09:10:00
09:40:00
08:40:00
11:40:00
11:40:00
11:30:00
12:15:00
11:50:00
12:05:00
10:25:00
10:10:00
10:15:00
10:35:00
10:50:00
10:45:00
04:25:00
04:05:00
06:45:00
06:40:00
06:00:00
05:55:00
08:05:00
08:00:00
08:00:00
08:05:00
07:55:00
07:55:00
08:20:00
07:20:00
06:50:00
06:45:00
07:10:00
18:00:00
18:00:00
17:55:00
18:10:00
18:10:00
17:05:00
17:10:00
17:35:00
17:30:00
19:10:00
19:30:00
18:30:00
18:20:00
18:45:00
18:45:00
18:35:00
14:25:00
14:20:00
14:45:00
14:50:00
12:50:00
12:50:00
12:30:00
12:40:00
13:25:00
13:00:00
13:05:00
16:55:00
17:00:00
15:20:00
20:10:00
21:50:00
21:55:00
22:15:00
22:15:00
20:10:00
22:35:00
22:30:00
22:25:00
22:25:00
22:20:00
22:20:00
18:15:00
17:45:00
18:10:00
03:10:00
03:15:00
21:35:00
20:15:00
20:15:00
21:55:00
21:55:00
21:45:00
22:25:00
22:05:00
12:35:00
20:00:00
20:00:00
12:00:00
16:00:00
16:00:00
16:05:00
15:40:00
16:10:00
16:10:00
16:20:00
16:15:00
16:20:00
15:00:00
14:30:00
14:45:00
14:35:00
15:35:00
15:10:00
15:20:00
15:15:00
15:15:00
11:25:00
11:35:00
11:10:00
11:05:00
11:05:00
10:55:00
10:50:00
10:40:00
16:55:00
16:55:00
17:05:00
16:40:00
16:50:00
17:10:00
17:20:00
08:30:00
08:25:00
08:25:00
08:35:00
08:05:00
07:50:00
08:10:00
08:10:00
09:25:00
14:25:00
09:25:00
09:30:00
10:05:00
09:55:00
10:00:00
08:45:00
14:25:00
13:45:00
13:40:00
13:40:00
13:40:00
13:50:00
13:50:00
07:15:00
07:10:00
06:55:00
07:00:00
07:05:00
07:20:00
07:25:00
07:25:00
07:30:00
06:50:00
01:55:00
02:35:00
02:25:00
01:25:00
01:25:00
01:30:00
09:05:00
09:00:00
09:00:00
08:40:00
08:50:00
08:45:00
16:20:00
16:15:00
16:15:00
16:10:00
16:10:00
16:05:00
17:00:00
16:55:00
14:45:00
14:50:00
14:40:00
14:55:00
14:05:00
14:30:00
14:35:00
14:25:00
15:20:00
21:05:00
21:00:00
21:30:00
21:25:00
17:50:00
17:50:00
17:35:00
17:45:00
18:30:00
18:35:00
12:30:00
12:30:00
12:30:00
12:30:00
13:15:00
13:35:00
13:50:00
13:55:00
13:10:00
21:00:00
20:55:00
19:25:00
19:30:00
12:40:00
12:35:00
11:40:00
12:15:00
18:25:00
19:05:00
13:30:00
14:05:00
15:35:00
09:55:00
08:20:00
08:25:00
10:05:00
11:05:00
11:10:00
11:05:00
11:00:00
11:10:00
11:15:00
10:30:00
10:30:00
10:45:00
10:35:00
10:35:00
12:50:00
12:25:00
11:40:00
11:35:00
11:35:00
11:35:00
16:35:00
16:35:00
16:30:00
14:00:00
14:05:00
15:25:00
15:20:00
18:00:00
17:55:00
17:55:00
18:15:00
17:30:00
17:25:00
17:50:00
19:55:00
20::00
15::00
22:25:00
20:35:00
21:45:00
21:45:00
21:45:00
15:10:00
13:25:00
13:25:00
13:35:00
13:20:00
13:45:00
13:50:00
16:10:00
16:45:00
16:50:00
23:40:00
23:30:00
15:25:00
15:30:00
11:05:00
11:00:00
11:00:00
10:40:00
10:45:00
10:55:00
11:55:00
10:05:00
10:15:00
20:10:00
20:15:00
12:15:00
12:10:00
12:10:00
18:20:00
18:05:00
19:50:00
19:05:00
06:15:00
06:20:00
05:15:00
05:10:00
07:20:00
07:20:00
07:20:00
07:15:00
07:15:00
07:30:00
07:25:00
06:55:00
07:05:00
07:00:00
07:00:00
18:50:00
02:05:00
02:10:00
02:15:00
02:20:00
35::00
25::00
08:35:00
09:40:00
07:45:00
08:30:00
08:25:00
08:25:00
08:30:00
08:30:00
21:45:00
22:10:00
22:00:00
21:15:00
21:10:00
21:40:00
23:50:00
23:45:00
23:35:00
23:35:00
22:30:00
22:25:00
19:45:00
19:55:00
20:00:00
20:50:00
21:00:00
20:10:00
20:15:00
20:10:00
09:45:00
16:45:00
16:55:00
17:10:00
17:35:00
17:15:00
17:15:00
16:10:00
15:55:00
16:00:00
16:20:00
16:25:00
18:25:00
18:20:00
18:45:00
17:50:00
18:00:00
18:15:00
18:10:00
18:05:00
13:00:00
13:05:00
12:25:00
12:30:00
10:25:00
10:25:00
10:20:00
10:20:00
10:35:00
10:15:00
10:15:00
10:05:00
11:10:00
10:45:00
10:50:00
10:55:00
15:05:00
15:15:00
14:45:00
14:45:00
15:45:00
15:20:00
13:35:00
13:25:00
14:20:00
14:10:00
16:30:00
16:20:00
18:05:00
18:05:00
18:00:00
14:00:00
14:05:00
13:25:00
13:10:00
13:15:00
16:00:00
15:40:00
15:40:00
15:40:00
15:45:00
16:15:00
16:15:00
16:15:00
16:10:00
15:25:00
15:35:00
15:30:00
21:40:00
21:45:00
21:30:00
21:30:00
20:25:00
21:05:00
20:55:00
23:00:00
23:00:00
23:40:00
23:35:00
22:20:00
22:20:00
18:30:00
18:35:00
18:35:00
19:55:00
20:15:00
20:15:00
20:10:00
20:10:00
20:10:00
19:50:00
19:45:00
19:40:00
09:50:00
09:55:00
09:30:00
09:25:00
10:00:00
09:10:00
09:15:00
09:05:00
12:25:00
12:20:00
12:30:00
12:30:00
12:05:00
12:05:00
12:00:00
12:05:00
13:00:00
13:00:00
12:55:00
13:00:00
12:35:00
12:40:00
12:45:00
11:20:00
11:00:00
11:45:00
11:55:00
11:25:00
11:30:00
11:30:00
11:35:00
07:10:00
07:15:00
07:05:00
07:30:00
07:25:00
06:05:00
06:50:00
06:45:00
06:55:00
06:40:00
08:05:00
08:05:00
08:05:00

In [142]:
arr_index = []
for index in data_result.index:
  if len(data_result.loc[index,'기준_시간_str_d']) != 8:
    arr_index.append(index)


arr_index

[17,
 113,
 114,
 868,
 902,
 1222,
 1584,
 1585,
 1661,
 1999,
 2000,
 2058,
 2059,
 2344,
 2345,
 2355,
 2357,
 2457,
 2544,
 2545,
 2775,
 4238,
 4348,
 4349,
 4350,
 4351,
 4412,
 4522,
 4523,
 4524,
 4525,
 4526,
 4527,
 4551,
 4552,
 4825,
 4826,
 4972,
 4974,
 4975,
 4976,
 4977,
 5093,
 5380,
 5381,
 5383,
 5384,
 5385,
 5595,
 5656,
 5657,
 5658,
 5659,
 5892,
 5893,
 6305,
 6306,
 6307,
 6308,
 6445,
 6515,
 6516,
 7004,
 7005,
 7105,
 7106,
 7447,
 7448,
 7512,
 7513,
 7514,
 7598,
 7599,
 7601,
 7783,
 7784,
 8231,
 8290,
 8291,
 8711,
 8712,
 8713,
 9191,
 9193,
 9545,
 9546,
 9547,
 9549,
 9550,
 9551,
 9552,
 9553,
 10520,
 10521,
 10832,
 10833,
 11559,
 11560,
 11561,
 11562,
 11851,
 11852,
 11853,
 11854,
 11893,
 11894,
 12240,
 12241,
 12242,
 12243,
 12443,
 12444,
 12445,
 12446,
 12447,
 12448,
 12769,
 12770,
 12771,
 12773,
 13248,
 13249,
 13362,
 13363,
 13479,
 13736,
 13737,
 13739,
 13740,
 13741,
 13858,
 13859,
 13860,
 13861,
 13862,
 13863,
 13934,
 14125,
 14126,
 14127,
 14128,
 14306,
 14307,
 14420,
 14447,
 14698,
 14699,
 14700,
 14701,
 14715,
 14716,
 15055,
 15056,
 15059,
 15240,
 15241,
 15242,
 15243,
 15248,
 15249,
 15418,
 15419,
 15420,
 15421,
 15513,
 15514,
 15516,
 15517,
 15518,
 15519,
 15520,
 15521,
 15593,
 15797,
 15798,
 15799,
 15800,
 15954,
 15955,
 15959,
 15960,
 16226,
 16227,
 16228,
 16229,
 16418,
 16428,
 16478,
 16481,
 16561,
 16562,
 16563,
 16564,
 16878,
 16879,
 17311,
 17334,
 17335,
 17336,
 17411,
 17412,
 17413,
 17414,
 17710,
 17711,
 17712,
 17713,
 17972,
 17973,
 17974,
 17975,
 17977,
 17978,
 17979,
 17980,
 17981,
 17982,
 18216,
 18217,
 18218,
 18219,
 18564,
 18567,
 18685,
 18686,
 18687,
 18688,
 18783,
 18878,
 18936,
 18949,
 19061,
 19124,
 19155,
 19158,
 19161,
 19178,
 19181,
 19197,
 19302,
 19350,
 19499,
 20066,
 20136,
 20257,
 20263,
 20333,
 20510,
 20642,
 20951,
 20963,
 21030,
 21052,
 21172,
 21181,
 21212,
 21236,
 21287,
 21293,
 21317,
 21348,
 21494,
 21525,
 21545,
 21635,
 21668,
 21864,
 21874,
 21914,
 21915,
 22163,
 22164,
 22185,
 22198,
 22330,
 22331,
 22428,
 22430,
 22633,
 22634,
 22838,
 23117,
 23118,
 23119,
 23120,
 23293,
 23294,
 23423,
 23424,
 23865,
 23866,
 23867,
 23868,
 24258,
 24361,
 24483,
 24514,
 24532,
 24543,
 24581,
 24582,
 24608,
 24614,
 24641,
 24654,
 24694,
 24695,
 24696,
 24786,
 24787,
 25047,
 25106,
 25499,
 25539,
 25548,
 25561,
 25580,
 25642,
 25716,
 25741,
 25749,
 25867,
 25967,
 26137,
 26161,
 26170,
 26178,
 26184,
 26194,
 26195,
 26209,
 26380,
 26451,
 26605,
 26613,
 26639,
 26643,
 26669,
 26675,
 26932,
 26943,
 27069,
 27087,
 27117,
 27127,
 27158,
 27213,
 27235,
 27268,
 27283,
 27285,
 27306,
 27316,
 27327,
 27329,
 27455,
 27510,
 27544,
 27556,
 27803,
 27860,
 27882,
 27883,
 27908,
 27917,
 27929,
 28191,
 28203,
 28227,
 28235,
 28344,
 28376,
 28423,
 28794,
 28823,
 28990,
 29026,
 29429,
 29447,
 29653,
 29690,
 29709,
 29742,
 29860,
 29899,
 29907,
 29943,
 30215,
 30250,
 30321,
 30322,
 30347,
 30355,
 30388,
 30413,
 30504,
 30691,
 30705,
 30707,
 30713,
 30787,
 30789,
 30793,
 30797,
 30803,
 30806,
 30849,
 30861,
 30887,
 30967,
 30994,
 31075,
 31080,
 31094,
 31099,
 31309,
 31314,
 31445,
 31777,
 32498,
 32519]

In [134]:
data_result.loc[arr_index,'기준_시간_d'] = data_result.loc[arr_index,'기준_시간_d'].str.replace('.0','')

In [148]:
arr_index = []
for index in data_result.index:
  if len(data_result.loc[index,'날짜']) != 17:
    arr_index.append(index)


arr_index

[17,
 4525,
 4526,
 10521,
 10832,
 14420,
 14447,
 15059,
 15516,
 15517,
 15954,
 15955,
 15960,
 16227,
 17311,
 17710,
 17712,
 17713,
 17977,
 18219,
 18878,
 18936,
 19155,
 19178,
 19181,
 20257,
 21030,
 21317,
 21525,
 22430,
 22633,
 22634,
 23866,
 23867,
 23868,
 24614,
 24641,
 24695,
 24696,
 25499,
 25539,
 25867,
 25967,
 26605,
 26675,
 27069,
 27268,
 28344,
 28794,
 29026,
 30887,
 31075,
 31314]

In [152]:
data_result['datetime'] = pd.to_datetime(data_result['날짜'])

In [155]:
data_result.drop(
  ['기준_시간_str',	'기준_시간_str_d', '기준_날짜_str', '날짜','기준_시간_d'],
  axis='columns',
  inplace=True
)

In [167]:
for index in data_result.index:
  data_result.loc[index,'hour'] = data_result.loc[index,'datetime'].hour

In [171]:
data_result.sort_values(
  by=['시작_대여소_ID','기준_날짜','hour']
).to_csv('../../Data/gtlee_data/sorted_data.csv',index=None)

In [ ]:
# 작업중
(data_result.시작_대여소_ID=='ST-3126') & (data_result.집계_기준 == '출발시간') & (data_result.)

,기준_날짜,집계_기준,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,기준_시간,datetime,hour
0,20240101,출발시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,1.0,4.0,612.0,1645.0,2024-01-01 16:45:00,16.0
1,20240101,도착시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,1.0,4.0,612.0,1650.0,2024-01-01 16:50:00,16.0
2,20240101,도착시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,2.0,7.0,1248.0,1635.0,2024-01-01 16:35:00,16.0
3,20240101,출발시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,2.0,7.0,1248.0,1630.0,2024-01-01 16:30:00,16.0
4,20240101,도착시간,ST-2263,진관동_108_6,ST-481,구산동_062_1,1.0,12.0,2992.0,1400.0,2024-01-01 14:00:00,14.0

In [ ]:
data_result['hour'] = data_result['datetime']

AttributeError: 'Series' object has no attribute 'hour'

In [101]:
data_result.drop(
  '기준_시간_int',
  axis='columns',
  inplace=True
)

In [107]:
data_result.drop(
  data_result[(data_result.전체_이용_분 == 0) & (data_result.전체_이용_거리 == 0)].index,
  axis='rows',
  inplace=True
)

In [108]:
data_result[(data_result.전체_이용_분 == 0) & (data_result.전체_이용_거리 == 0)].index

Index([], dtype='int64')

In [110]:
data_result.loc[:,'기준_날짜_str'] = data_result.loc[:,'기준_날짜'].astype(str)

In [140]:
data_result.loc[arr_index,'날짜'] = data_result.loc[arr_index,'기준_날짜_str'] + ' ' + data_result.loc[arr_index,'기준_시간_d']

In [141]:
data_result.loc[arr_index]

,기준_날짜,집계_기준,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,기준_시간,기준_시간_str,기준_시간_str_d,기준_날짜_str,날짜,기준_시간_d
17,20240101,출발시간,ST-2263,진관동_108_6,ST-1483,진관동_038_4,1.0,56.0,8703.0,5.0,5,5::00,20240101,20240101 00:00:5,00:00:5
113,20240102,도착시간,ST-2263,진관동_108_6,ST-2261,진관동_108_5,1.0,4.0,530.0,45.0,45,45::00,20240102,20240102 00:00:45,00:00:45
114,20240102,출발시간,ST-2263,진관동_108_6,ST-2261,진관동_108_5,1.0,4.0,530.0,40.0,40,40::00,20240102,20240102 00:00:40,00:00:40
868,20240121,출발시간,ST-3126,진관동_096_1,ST-1028,진관동_038_2,1.0,10.0,2384.0,55.0,55,55::00,20240121,20240121 00:00:55,00:00:55
902,20240122,출발시간,ST-3126,진관동_096_1,ST-1028,진관동_038_2,1.0,10.0,2144.0,55.0,55,55::00,20240122,20240122 00:00:55,00:00:55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31314,20241209,출발시간,ST-3126,진관동_076_1,ST-453,진관동_011_3,1.0,17.0,979.0,0.0,0,0::00,20241209,20241209 00:00:0,00:00:0
31445,20241210,출발시간,ST-1027,진관동_006_1,ST-479,역촌동_080_1,1.0,15.0,4180.0,45.0,45,45::00,20241210,20241210 00:00:45,00:00:45
31777,20241217,출발시간,ST-3126,진관동_076_1,ST-1331,응암3동_023_1,1.0,39.0,5937.0,55.0,55,55::00,20241217,20241217 00:00:55,00:00:55
32498,20241231,출발시간,ST-3126,진관동_076_1,ST-453,진관동_011_3,1.0,4.0,605.0,20.0,20,20::00,20241231,20241231 00:00:20,00:00:20
32519,20241231,도착시간,ST-3126,진관동_076_1,ST-453,진관동_011_3,1.0,4.0,605.0,25.0,25,25::00,20241231,20241231 00:00:25,00:00:25

In [115]:
pd.to_datetime(data_result['날짜'])

ValueError: time data "20240101 5::00" doesn't match format "%Y%m%d %H:%M:%S". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [73]:
pd.to_datetime(data_result['기준_날짜_str'].astype(str) +' '+ data_result['기준_시간_str_dd'])

ValueError: time data "2024-01-01 40:0:00" doesn't match format "%Y-%m-%d %H:%M:%S". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [7]:
data_result.info()

<class 'pandas.DataFrame'>
RangeIndex: 32530 entries, 0 to 32529
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   기준_날짜      32530 non-null  int64
 1   집계_기준      32530 non-null  str
 2   시작_대여소_ID  32530 non-null  str
 3   시작_대여소명    32530 non-null  str
 4   종료_대여소_ID  32530 non-null  str
 5   종료_대여소명    32437 non-null  str
 6   전체_건수      32530 non-null  float64
 7   전체_이용_분    32213 non-null  float64
 8   전체_이용_거리   32213 non-null  float64
 9   기준_시간      32530 non-null  float64
 10  기준_날짜_str  2355 non-null   str
dtypes: float64(4), int64(1), str(6)
memory usage: 4.5 MB

In [ ]:
xx = data_result.groupby(by=['집계_기준','지','시작_대여소_ID']).value_counts()

In [80]:
xx

집계_기준  시작_대여소_ID  기준_날짜     시작_대여소명    종료_대여소_ID  종료_대여소명     전체_건수  전체_이용_분  전체_이용_거리  기준_시간
도착시간   ST-1027    20240720  진관동_038_1  ST-2259    진관동_001_1   1.0    21.0     2640.0    1110.0    3
                  20240802  진관동_006_1  ST-453     진관동_011_3   1.0    5.0      1450.0    1735.0    3
                  20240803  진관동_006_1  ST-456     갈현2동_014_1  1.0    14.0     3670.0    1745.0    3
                  20240805  진관동_006_1  ST-2263    진관동_004_2   1.0    4.0      975.0     1535.0    3
                  20240719  진관동_038_1  ST-453     진관동_038_9   1.0    6.0      1264.0    1335.0    2
                                                                                                 ..
출발시간   ST-3126    20241231  진관동_076_1  ST-2782    갈현1동_002_2  1.0    9.0      1812.0    1650.0    1
                                       ST-1483    진관동_108_1   1.0    23.0     1240.0    1050.0    1
                                       ST-2261    진관동_106_1   2.0    15.0     1826.0    1740.0    1
                                       ST-1483    진관동_108_1   1.0    43.0     1560.0    1900.0    1
                                       ST-453     진관동_011_3   1.0    3.0      639.0     735.0     1
Name: count, Length: 31877, dtype: int64

In [ ]:
total = data_result['연간_전체건수'].sum()

In [17]:
data_result.drop(
  ['전체_건수',	'전체_이용_분','전체_이용_거리'],
  axis='columns',
  inplace=True
)

In [ ]:
# 분기를 넣기
# data_result.loc[data_result[data_result.기준_날짜 < 20240401].index,'분기'] = '1분기'
# data_result.loc[data_result[(data_result.기준_날짜 >= 20240401)&(data_result.기준_날짜 < 20240701)].index,'분기'] = '2분기'
# data_result.loc[data_result[(data_result.기준_날짜 >= 20240701) & (data_result.기준_날짜 < 20241001)].index,'분기'] = '3분기'
# data_result.loc[data_result[data_result.기준_날짜 >= 20241001].index,'분기'] = '4분기'

In [72]:
# 기준시간을 따로 뽑아야 함. 
# 요일로 나오게 해야 함.
# 주말 여부 
# 
data_result.head()

,기준_날짜,집계_기준,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,기준_시간
0,20240101,출발시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,1.0,4.0,612.0,1645.0
1,20240101,도착시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,1.0,4.0,612.0,1650.0
2,20240101,도착시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,2.0,7.0,1248.0,1635.0
3,20240101,출발시간,ST-3126,진관동_096_1,ST-453,진관동_038_9,2.0,7.0,1248.0,1630.0
4,20240101,도착시간,ST-2263,진관동_108_6,ST-481,구산동_062_1,1.0,12.0,2992.0,1400.0

In [ ]:
data_result.groupby(by=[기준_날짜',])

KeyError: 'Only the Series name can be used for the key in Series dtype mappings.'

In [ ]:
str = data_result.기준_시간

KeyError: 'Only the Series name can be used for the key in Series dtype mappings.'

RangeIndex(start=0, stop=32530, step=1)

In [68]:
data_result['기준_날짜'] = data_result['기준_날짜'].astype(str)

KeyError: 'Only the Series name can be used for the key in Series dtype mappings.'

In [ ]:
str.str.split('.')[0][0]

'1645'

In [5]:
# 3구역 중 필수 station 3개
mydata = df[(df.시작_대여소_ID == 'ST-1027') | (df.시작_대여소_ID =='ST-2263') | (df.시작_대여소_ID =='ST-3126')]

AttributeError: 'DataFrame' object has no attribute '시작_대여소_ID'

In [ ]:
import folium

In [ ]:
seoul_map = folium.Map(
  location=[37.55,126.98],
  zoom_start=11
)

for 대여소_ID,위도,경도,연간_전체건수 in zip(data_result.대여소_ID, data_result.위도,data_result.경도,data_result.연간_전체건수):
  popup = folium.Popup(대여소_ID, max_width=200)
  folium.Marker(
    [위도, 경도],
    popup=popup
  ).add_to(seoul_map)

  
  folium.CircleMarker(
    [위도, 경도],
    radius=연간_전체건수/total*100*2.5,
    color = 'skyblue',
    fill=True,
    fill_color='skyblue',
    fill_opacity=0.4,
    tooltip=f"전체건수{연간_전체건수}",
  ).add_to(seoul_map)

  




seoul_map