In [ ]:
import pandas as pd
import numpy as np
import warnings 
import pyarrow 
warnings.filterwarnings('ignore')

In [5]:
col = ['ST-464','ST-481','ST-479','ST-2247','ST-2252','ST-2425','ST-1027','ST-2263','ST-3126','ST-1035','ST-454','ST-471','ST-1024','ST-1023','ST-1483','ST-1034','ST-462','ST-2264']

df2024 = pd.read_parquet('../../Data/data.parquet')
df2025 = pd.read_parquet('../../Data/2025_data.parquet')

In [9]:
total = pd.concat([df2024,df2025],axis=0)
total

,기준_날짜,집계_기준,기준_시간대,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,대여소_ID,주소1,주소2,위도,경도
0,20240101,출발시간,1735.0,ST-479,역촌동_068_1,ST-462,신사2동_025_1,2.0,151.0,21873.0,ST-479,서울특별시 은평구 역촌동 45-34,역촌파출소,37.604736,126.915337
1,20240101,도착시간,1705.0,ST-455,응암1동_032_1,ST-2779,역촌동_030_1,1.0,3.0,102.0,ST-455,서울특별시 은평구 은평로 85 CJ드림시티,NaN,37.599495,126.916985
2,20240101,도착시간,1705.0,ST-460,응암3동_017_1,ST-2425,신사1동_036_1,1.0,11.0,550.0,ST-460,서울특별시 은평구 응암동 604-5,응암오거리,37.589661,126.916946
3,20240101,도착시간,1705.0,ST-461,응암1동_032_2,ST-2425,신사1동_036_1,1.0,15.0,1582.0,ST-461,서울특별시 은평구 응암동 90-15,이마트 은평점,37.600700,126.920128
4,20240101,도착시간,1705.0,ST-479,역촌동_068_1,ST-479,역촌동_068_1,1.0,22.0,2526.0,ST-479,서울특별시 은평구 역촌동 45-34,역촌파출소,37.604736,126.915337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1853023,20251231,도착시간,1740.0,ST-465,응암1동_059_1,ST-2250,녹번동_021_1,1.0,4.0,870.0,NaN,NaN,NaN,NaN,NaN
1853024,20251231,도착시간,245.0,ST-2153,신수동_027_1,ST-3095,증산동_004_1,1.0,39.0,5744.0,NaN,NaN,NaN,NaN,NaN
1853025,20251231,도착시간,1425.0,ST-479,역촌동_080_1,ST-459,녹번동_043_1,1.0,18.0,1306.0,NaN,NaN,NaN,NaN,NaN
1853026,20251231,도착시간,950.0,ST-3279,수색동_004_2,ST-3239,여의동_006_8,1.0,52.0,10431.0,NaN,NaN,NaN,NaN,NaN
1853027,20251231,도착시간,1950.0,ST-455,응암1동_023_1,ST-460,응암3동_007_1,1.0,6.0,1162.0,NaN,NaN,NaN,NaN,NaN

In [12]:
cond1 = (total['시작_대여소_ID'].isin(col)) & (total['집계_기준'] == '출발시간')
cond2 = (total['종료_대여소_ID'].isin(col)) & (total['집계_기준'] == '도착시간')

result = total[cond1 | cond2]
# df_section6['시'] = df_section6['기준_시간'] / 100
# df_section6['분'] = df_section6['기준_시간'] % 100
# df_section6['시'] = df_section6['시'].astype(int)
# df_section6['분'] = df_section6['분'].astype(int)
result.sort_values(['기준_날짜'],ascending=True,inplace=True)
result.reset_index(drop=True, inplace=True)
result

,기준_날짜,집계_기준,기준_시간대,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,대여소_ID,주소1,주소2,위도,경도
0,20240101,출발시간,1735.0,ST-479,역촌동_068_1,ST-462,신사2동_025_1,2.0,151.0,21873.0,ST-479,서울특별시 은평구 역촌동 45-34,역촌파출소,37.604736,126.915337
1,20240101,출발시간,1410.0,ST-464,역촌동_022_1,ST-455,응암1동_032_1,1.0,7.0,1143.0,ST-464,서울특별시 은평구 역촌동 15-40,평생학습관 앞,37.607849,126.921326
2,20240101,출발시간,1410.0,ST-479,역촌동_068_1,ST-461,응암1동_032_2,1.0,4.0,649.0,ST-479,서울특별시 은평구 역촌동 45-34,역촌파출소,37.604736,126.915337
3,20240101,출발시간,1410.0,ST-481,구산동_062_1,ST-89,성산2동_041_5,1.0,48.0,5667.0,ST-481,서울특별시 은평구 서오릉로 163,LG서비스 역촌점,37.612484,126.914879
4,20240101,출발시간,1410.0,ST-1483,진관동_038_4,ST-1329,진관동_031_1,1.0,2.0,0.0,ST-1483,서울특별시 은평구 진관2로 15-46,은평구 진관2로 15-46,37.639259,126.918907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949132,20251231,출발시간,1200.0,ST-1035,불광2동_020_1,ST-481,구산동_029_1,1.0,7.0,1117.0,NaN,NaN,NaN,NaN,NaN
949133,20251231,출발시간,935.0,ST-2264,역촌동_068_1,ST-480,구산동_043_1,1.0,10.0,1190.0,NaN,NaN,NaN,NaN,NaN
949134,20251231,출발시간,1325.0,ST-462,응암3동_002_2,ST-3388,망원1동_005_2,1.0,26.0,4966.0,NaN,NaN,NaN,NaN,NaN
949135,20251231,출발시간,620.0,ST-479,역촌동_080_1,ST-2776,녹번동_060_1,1.0,20.0,2490.0,NaN,NaN,NaN,NaN,NaN
949136,20251231,도착시간,700.0,ST-226,북가좌1동_026_1,ST-1034,증산동_030_1,1.0,4.0,634.0,NaN,NaN,NaN,NaN,NaN

In [13]:
result.to_csv('../../Data/total_data.csv',index=None)