In [12]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import seaborn as sns
import platform

if platform.system() == "Darwin":   # macOS
    plt.rcParams["font.family"] = "AppleGothic"
else:                               # Windows / Linux
    plt.rcParams["font.family"] = "Malgun Gothic"

plt.rcParams["axes.unicode_minus"] = False

In [16]:
df = pd.read_parquet("/Users/restitutor/Documents/Restitutor/Workspace/Flutter-Python/Python/EP_cycle_stations/Data/sort_data/2024_data_6station.parquet")
df.head()

,기준_날짜,시간대,집계_기준,시작_대여소_ID,종료_대여소_ID,전체_건수,전체_이용_분,전체_이용_거리,온도,습도,불쾌지수,강수량,적설량
0,2024-01-01,16,출발시간,ST-460,ST-2425,1.0,0 days 00:11:00,550.0,6.1,65,45.87135,0.0,0.0
1,2024-01-01,16,출발시간,ST-461,ST-2425,1.0,0 days 00:15:00,1582.0,6.1,65,45.87135,0.0,0.0
2,2024-01-01,17,출발시간,ST-1036,ST-454,1.0,0 days 00:03:00,762.0,4.3,78,41.94946,0.0,0.0
3,2024-01-01,16,출발시간,ST-3126,ST-453,1.0,0 days 00:04:00,612.0,6.1,65,45.87135,0.0,0.0
4,2024-01-01,16,출발시간,ST-465,ST-1482,1.0,0 days 00:07:00,1267.0,6.1,65,45.87135,0.0,0.0

In [18]:
df = pd.read_csv("/Users/restitutor/Documents/Restitutor/Workspace/Flutter-Python/Python/EP_cycle_stations/Data/sort_data/preprocessed_6station/ST-454.csv")
df.head()

,기준_날짜,시간대,집계_기준,시작_대여소_ID,종료_대여소_ID,전체_이용_분,전체_이용_거리,온도,습도,강수량,...,is_noon,is_rushhour,month,residential_index,business_index,tourism_index,transit_index,commute_in_index,commute_out_index,snow_flag
0,2024-01-01,0,출발시간,ST-1029,ST-454,0 days 00:11:00,2068.0,-2.7,92,0.0,...,0,0,1,0.029018,0.030956,0.020744,0.0,0.0,0.0,0
1,2024-01-01,0,출발시간,ST-1029,ST-454,0 days 00:11:00,2068.0,-2.7,92,0.0,...,0,0,1,0.029018,0.030956,0.020744,0.0,0.0,0.0,0
2,2024-01-01,0,출발시간,ST-454,ST-1025,0 days 00:12:00,1960.0,-2.7,92,0.0,...,0,0,1,0.029018,0.030956,0.020744,0.0,0.0,0.0,0
3,2024-01-01,0,출발시간,ST-454,ST-1025,0 days 00:12:00,1960.0,-2.7,92,0.0,...,0,0,1,0.029018,0.030956,0.020744,0.0,0.0,0.0,0
4,2024-01-01,0,출발시간,ST-454,ST-1036,0 days 00:05:00,860.0,-2.7,92,0.0,...,0,0,1,0.029018,0.030956,0.020744,0.0,0.0,0.0,0